SELECT "GK" AS position, 1 AS position_order
UNION ALL SELECT "SW" AS position, 2 AS position_order
UNION ALL SELECT "RWB" AS position, 3 AS position_order
UNION ALL SELECT "RB" AS position, 4 AS position_order
UNION ALL SELECT "RCB" AS position, 5 AS position_order
UNION ALL SELECT "CB" AS position, 6 AS position_order
UNION ALL SELECT "LCB" AS position, 7 AS position_order
UNION ALL SELECT "LB" AS position, 8 AS position_order
UNION ALL SELECT "LWB" AS position, 9 AS position_order
UNION ALL SELECT "RDM" AS position, 10 AS position_order
UNION ALL SELECT "CDM" AS position, 11 AS position_order
UNION ALL SELECT "LDM" AS position, 12 AS position_order
UNION ALL SELECT "RM" AS position, 13 AS position_order
UNION ALL SELECT "RCM" AS position, 14 AS position_order
UNION ALL SELECT "CM" AS position, 15 AS position_order
UNION ALL SELECT "LCM" AS position, 16 AS position_order
UNION ALL SELECT "LM" AS position, 17 AS position_order
UNION ALL SELECT "RW" AS position, 18 AS position_order
UNION ALL SELECT "RAM" AS position, 19 AS position_order
UNION ALL SELECT "CAM" AS position, 20 AS position_order
UNION ALL SELECT "LAM" AS position, 21 AS position_order
UNION ALL SELECT "LW" AS position, 22 AS position_order
UNION ALL SELECT "RF" AS position, 23 AS position_order
UNION ALL SELECT "RS" AS position, 24 AS position_order
UNION ALL SELECT "CF" AS position, 25 AS position_order
UNION ALL SELECT "LS" AS position, 26 AS position_order
UNION ALL SELECT "LF" AS position, 27 AS position_order
UNION ALL SELECT "ST" AS position, 28 AS position_order